version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install --upgrade aws-sam-cli
  build:
    commands:
      - sam build --use-container
  post_build:
    commands:
      - sam package --output-template-file $SAM_OUTPUT_TEMPLATE --s3-bucket $ARTIFACT_BUCKET
artifacts:
  files:
    - $SAM_OUTPUT_TEMPLATE
